name: proteinBERT Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        pip install -r dependencies.txt
        wget -P preprocess/ ftp://ftp.cs.huji.ac.il/users/nadavb/protein_bert/epoch_92400_sample_23500000.pkl
    - name: run proteinBERT.py
      run: |
        python preprocess/proteinBERT.py
    - name: Upload results
      uses: actions/upload-artifact@v2
      with:
        name: results
        path: ./data/global_representations.npy
